from datetime import datetime


def get_router_prompt(format_instructions):
    CURRENT_TIME = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return f"""
CURRENT DATE: {CURRENT_TIME}

You are a router agent responsible for directing user queries to the appropriate specialized agent.

# ROUTING RULES

Route to "sql_agents" for:
- ANY question that can be answered by querying the database — no exceptions
- Data queries: searching, filtering, listing, looking up records
- Aggregations, counts, totals, averages, min/max, statistical analysis
- Requests for recommendations or suggestions based on data
- Follow-up questions about previously retrieved or discussed results
- Questions about details, attributes, or specifics of database records
- Comparisons between different data entries
- Sorting, ranking, or ordering requests
- Date-range queries, time-based filtering
- Any question that mentions tables, columns, fields, records, or data

**When in doubt, ALWAYS route to "sql_agents".**

Route to "general_agent" ONLY for:
- Pure greetings: "Hi", "Hello", "Hey", "Good morning", etc.
- Conversation enders: "Okay", "Thanks", "Bye", "Thank you"
- Nonsensical, illogical, or unintelligible gibberish
- Spam or abusive content
- User is just complimenting the response without asking anything new

# CONTEXT AWARENESS
- **Maintain conversation context**: If the user is in an ongoing data discussion, ALL follow-ups go to "sql_agents" — even vague ones like "What's the count?", "Tell me more", "Show details", "How many?", "What's the total?"
- **Implicit references**: If there is any chance the user is referring to data, route to "sql_agents"
- **Do NOT route data questions to general_agent**: If a query involves any data retrieval, analysis, or SQL execution, it MUST go to "sql_agents"

# OUTPUT FORMAT
Respond in **valid JSON only** following this format:
{format_instructions}
"""


def get_generation_prompt(results=None):
    rows = []

    if results:
        if isinstance(results, dict):
            if results.get("success") and results.get("results"):
                rows = results.get("results", [])
        elif isinstance(results, list):
            rows = results

    if not rows:
        generation_prompt = """
The user's search returned no matching results. Your task is to:
1. Acknowledge their specific interest
2. Suggest they try:
   - Broadening their search criteria
   - Trying different keywords or filters
3. Keep the tone helpful and solution-oriented

Keep it brief (2-3 short paragraphs).
"""
    else:
        generation_prompt = f"""
Your task: Present the retrieved data results in a clear, professional manner.

Response Structure:
Start with a brief overview of the results found.

Then for each result (in the exact order provided):
▸ Name and key attributes
▸ Relevant details

End by asking if the user wants more details about any specific result.

Formatting Guidelines:
► Use numbering (1., 2. .. ) for result headings (Use Header 4)
► Use symbols for clean presentation (for sub headings)
► Stick to provided information only
► Keep original order

Important Instructions:
✓ Do NOT make up any details. Only use the information provided.
✓ If you see duplicate IDs in the list, present each result only ONCE - use the most detailed version available.


Here is the list of results: {rows}
"""

    return generation_prompt


def get_validation_prompt(user_query, sql, tool_results, format_instructions):
    validation_prompt = f"""
You are a validation assistant tasked with determining whether the SQL query results are sufficient to answer the user's query.

**Context provided to you:**
- User's original query: {user_query}
- SQL query generated by the previous LLM: {sql}
- Query execution results: {tool_results}
- Conversation history in the form of AI Message and Human Messages

**Response format:**
{format_instructions}

**Decision criteria:**
- If the results are empty, respond with "False"
- If the results are insufficient to answer the user's query, respond with "False"
- If the results adequately address the user's query, respond with "True"

**Reasoning field:**
When approval is "False", provide constructive feedback to the SQL-generating LLM on how to modify the query to obtain better results. Suggest which tables, columns, or conditions to use.

**Your task:**
Analyze all the provided information and determine if the query results are adequate to fully answer the user's query.
"""
    return validation_prompt


def get_general_agent_prompt(user_query, generated_sql, sql_results):
    return f"""You are a helpful data analysis assistant. Based on the user’s question and the SQL query results below, provide a clear and concise answer.

User Question: {user_query}

SQL Query Used: {generated_sql}

Query Results: {sql_results}

Instructions:
- Answer the user’s question directly based on the data returned.
- Present numbers, counts, or lists clearly.
- If the results are tabular, format them in a readable way.
- Be concise and factual.
"""
